services:
  - type: web
    name: filedrive
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        value: sqlite:///filedrive.db
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true 